---
title: "Experimental evolution analyses"
author: "Hugo Scharfenstein"
date: "`r Sys.Date()`"
output: html_document
---

Load packages
```{r}
#Load packages
library(tidyverse)
library(ggpubr)
library(readxl)
library(forcats)
```

Import data
```{r}
#Import data into R
EE.df <- read_xlsx("./GCB dataset.xlsx", sheet = 1)

#Labels for facets
treatment.labs <- c("Diurnal temperature fluctuations", "Temperature fluctations every 2-3 generations", "Temperature fluctations every 4-5 generations", "Continuous exposure to elevated temperatures", "Continuous exposure to ambient temperature")
names(treatment.labs) <- c("TP1", "TP2", "TP3", "TP4", "TP5")
as.character(EE.df$Growth_temperature)
```

Calculate total & cumulative generations till start of thermal performance assay
```{r}
#Calculate total & cumulative generations till start of thermal performance assay
Gen.df <- EE.df %>%
  filter(Time_week <= 110) %>%
  group_by(Lineage) %>% 
  mutate(Total_generations = sum(Generations)) %>%
  group_by(Lineage, Growth_temperature) %>% 
  mutate(Cumulative_generations = sum(Generations)) %>%
  dplyr::select(c(EE_treatment, Lineage, Replicate, Growth_temperature, Cumulative_generations, Total_generations)) %>% 
  distinct() %>%
  mutate_if(is.numeric, ~round(., 1)) %>%
  ungroup()

#Plot cumulative generations elapsed
Cum_gen.plot <- Gen.df %>%
  filter(Cumulative_generations != 0) %>%
  mutate(Growth_temperature = as.character(Growth_temperature)) %>%
  ggplot(aes(y = Cumulative_generations, x = Lineage, fill = forcats::fct_rev(Growth_temperature))) +
  geom_bar(stat = "identity") +
  scale_y_continuous('Cumulative generations', expand = c(0,0), limits = c(0,95), breaks = 0:100*10) +
  scale_x_discrete('Lineage', expand = c(0,0)) +
  scale_fill_manual(values = c("#d73027", "#f46d43", "#fee090", "#abd9e9","#4575b4","#000000")) +
  annotate("text",
           x = c(3.5, 9.5, 15.5, 21.5, 27.5), 
           y = c(67, 76, 67, 60, 93), 
           label = c('TP1', 'TP2', 'TP3', 'TP4', 'TP5'), size = 5) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major.x = element_blank(),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.position = 'top',
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(angle = 45, hjust=1, size = 12, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face = "bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        labs(fill = "Temperature (°C)") +
        guides(fill = guide_legend(nrow = 1))
Cum_gen.plot

#Plot total generations elapsed
Tot_gen.plot <- Gen.df %>%
  dplyr::select(-c(Cumulative_generations, Growth_temperature)) %>%
  distinct() %>%
  ggplot(aes(y = Total_generations, x = EE_treatment)) +
  geom_boxplot(fill = 'darkgrey') +
  scale_y_continuous('Total generations', expand = c(0,0), limits = c(55, 95)) +
  scale_x_discrete('Experimental evolution treatment', expand = c(0,0)) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face = "bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        labs(fill = "Temperature (°C)") +
        guides(fill = guide_legend(nrow = 1))
Tot_gen.plot
```

Calculate total & cumulative days under thermal selection till start of thermal performance assay
```{r}
Tslc.df <- EE.df %>%
  filter(Growth_temperature != 27) %>%
  filter(Time_week <= 110) %>%
  group_by(Lineage) %>%
  mutate(Total_temp_selec = max(Cumul_temp_selec)) %>%
  group_by(Lineage, Growth_temperature) %>% 
  mutate(Time_at_temp = sum(Days_temp_selec)) %>%
  dplyr::select(c(EE_treatment, Lineage, Replicate, Growth_temperature, Total_temp_selec, Time_at_temp)) %>%
  ungroup() %>%
  distinct()

#Plot time under thermal selection
Tslc.plot <- Tslc.df %>%
  dplyr::select(EE_treatment, Growth_temperature, Time_at_temp) %>%
  distinct() %>%
  mutate(Time_at_temp_weeks = Time_at_temp/7) %>%
  mutate(Growth_temperature = as.character(Growth_temperature)) %>%
  ggplot(aes(y = Time_at_temp_weeks, x = EE_treatment, fill = forcats::fct_rev(Growth_temperature))) +
  geom_bar(stat = "identity") +
  scale_y_continuous('Time under thermal selection (weeks)', expand = c(0,0)) + 
  scale_x_discrete('Experimental evolution treatment', expand = c(0,0)) +
  scale_fill_manual(values = c("#a50026", "#d73027", "#f46d43", "#fee090", "#abd9e9","#4575b4")) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major.x = element_blank(),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.position = 'top',
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face = "bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        labs(fill = "Temperature (°C)") +
        guides(fill = guide_legend(nrow = 1))
Tslc.plot
```

Performance (growth rate and Fv/Fm) at elevated temperatures
```{r}
Grow.plot <- EE.df %>%
  filter(Growth_temperature != 27) %>%
  ggplot(aes(y=GrowthR, x=Growth_temperature, fill=EE_treatment, group=interaction(Growth_temperature, EE_treatment))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.5) +
  geom_boxplot(position = position_dodge2(width = 1, preserve = "single")) +
  scale_x_continuous('Temperature (°C)', expand = c(0,0)) +
  scale_y_continuous(expression(bold(Growth~rate~(d^{"-1"}))), 
                     expand = c(0,0), 
                     limits=c(-0.1,0.1), 
                     breaks = seq(-0.1,0.1, by = 0.05)) +
  scale_fill_manual(values = c("#8B0000","#E4B031","#26727B","#4770B3", "#58595b")) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.position = 'top',
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face = "bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        labs(fill = "Experimental evolution treatment") +
        guides(fill = guide_legend(nrow = 1))
Grow.plot

Phot.plot <- EE.df %>%
  filter(Growth_temperature != 27) %>%
  ggplot(aes(y=FvFm, x=Growth_temperature, fill=EE_treatment, group=interaction(Growth_temperature, EE_treatment))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.5) +
  geom_boxplot(position = position_dodge2(width = 1, preserve = "single")) +
  scale_x_continuous('Temperature (°C)', expand = c(0,0)) +
  scale_y_continuous(expression(bold(Maximum~quantum~yield~(F[v]/F[m]))), 
                     expand=c(0,0), 
                     limits=c(0.2,0.6), 
                     breaks = seq(0,0.7, by = 0.1)) +
  scale_fill_manual(values = c("#8B0000","#E4B031","#26727B","#4770B3", "#58595b")) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.position = 'top',
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face = "bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        labs(fill = "Experimental evolution treatment") +
        guides(fill = guide_legend(nrow = 1))
Phot.plot
```

Growth rate over time
```{r}
#Plot growth rate over time
GrowR.plot <- EE.df %>%
  unite('TP_temp', EE_treatment, Growth_temperature, remove = FALSE) %>%
  mutate(TP_planned = case_when(str_detect(TP_temp, 'TP1_27') ~ 'No',
                                str_detect(TP_temp, 'TP4_27') ~ 'No',
                                TRUE ~ 'Yes')) %>%
  ggplot(aes(y = GrowthR, x = Time_week)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.5) +
  geom_vline(xintercept = 110, linetype = 'solid', color = 'grey', size = 0.5) +
  geom_smooth(method=mgcv::gam, formula = y~s(x, bs = "cs", k = -1), se = T, size = 00.5, colour = "black") +
  geom_point(aes(color = as.character(Growth_temperature), shape = TP_planned), size = 1.5) +
  facet_grid(EE_treatment~.) +
  scale_shape_manual(values=c(4, 19))+
  scale_x_continuous('Time (weeks)', breaks=0:130*10, expand=c(0,0), limits=c(0,123)) +
  scale_y_continuous(expression(bold(Growth~rate~(d^{"-1"}))), expand=c(0,0), limits=c(-0.1, 0.15)) +
  scale_colour_manual(values=c("#000000","#4575b4","#abd9e9","#fee090","#f46d43","#d73027", "#a50026")) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(),
        panel.spacing = unit(0.8, "lines"),
        strip.text.y = element_text(size = 14, face = "bold"),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 14),
        legend.position = 'top',
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face = "bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        labs(colour = "Temperature (°C)") +
        guides(shape = 'none', colour = guide_legend(nrow = 1, override.aes = list(size=3)))
GrowR.plot
```

Combine plots
```{r}
Time.plots <- ggarrange(Tot_gen.plot + rremove("xlab"),
                        Tslc.plot + rremove("legend"),
                        labels = c("B", "C"),
                        heights = c(1, 1),
                        widths = c(1, 1),
                        ncol = 1,
                        align = "hv")
Time.plots

Grow_time.plots <- ggarrange(GrowR.plot,
                             Time.plots,
                             common.legend = TRUE,
                             labels = c("A"),
                             heights = c(1, 1, 1),
                             widths = c(1, 0.5, 0.5),
                             ncol = 2,
                             align = "hv")
Grow_time.plots

Grow_phot.plots <- ggarrange(Grow.plot,
                             Phot.plot,
                             common.legend = TRUE,
                             labels = c("A", "B"),
                             heights = c(1, 1),
                             widths = c(1, 1),
                             nrow = 1,
                             align = "hv")
Grow_phot.plots
```

Save the plots
```{r}
ggsave(plot = Grow_phot.plots, "EE trait performances.pdf", 
       path = "./",
       width = 10,
       height = 5,
       units = 'in',
       dpi = 300)

ggsave(plot = Grow_time.plots, "EE growth & time.pdf", 
       path = "./",
       width = 12.5,
       height = 10,
       units = 'in',
       dpi = 300)

ggsave(plot = Cum_gen.plot, "EE cumulative generations.pdf", 
       path = "./",
       width = 10,
       height = 7.5,
       units = 'in',
       dpi = 300)
```
