---
title: "TPA - FvFm analysis"
author: "Hugo Scharfenstein"
date: "`r Sys.Date()`"
output: html_document
---

# Load packages
```{r}
#Data import and export packages
library(readxl)
library(writexl)
#Data wrangling packages
library(tidyverse)
#Data visualisation packages
library(SciViews)
library(ggpubr)
library(cowplot)
```

# Import data and cleanup
```{r}
FvFm.df <- read_xlsx("./Physiological datasets - EE & TPA.xlsx", sheet = 5)

#Relevel nutrient treatments
FvFm.df$Growth_temperature <- ordered(FvFm.df$Growth_temperature, levels = c('21', '23', '25', '27', '29', '31', '33'))

#Prepare labels for plot facets
growth.labs <- c("Growth cycle 1", "Growth cycle 2")
names(growth.labs) <- c('1', "2")
temperature.labs <- c('21°C', '23°C', '25°C', '27°C', '29°C', '31°C', '33°C')
names(temperature.labs) <- c('21', '23', '25', '27', '29', '31', '33')
treatment.labs <- c('Fluc-short', 'Fluc-med', 'Fluc-long', 'Cont-ele', 'Cont-amb')
names(treatment.labs) <- c('TP1', 'TP2', 'TP3', 'TP4', 'TP5')
```

# Fv/Fm analyses
```{r}
#Calculate median Fv/Fm from technical replicates
FvFm.df2 <- FvFm.df %>%
  filter(FvFm > 0)  %>%
  group_by(Nutrient_treatment, Measurement_date, Growth_temperature, Lineage) %>%
  mutate(FvFm = median(FvFm)) %>%
  dplyr::select(!c(Plate, Well, AOI)) %>%
  distinct() %>%
  mutate(across(where(is.numeric), ~ round(., 3))) %>%
  ungroup()

#Keep only timepoints corresponding to middle of exponential phase in second growth cycle
FvFm.df3 <- FvFm.df2 %>%
  filter(Nutrient_treatment == 'IMK') %>%
  filter(Measurement_date != '21.3.2023' & Measurement_date != '1.3.2023' & Measurement_date != '23.2.2023') %>%
  filter(Growth_cycle == 2) %>%
  filter(Growth_temperature == 31 | Growth_temperature == 29 | Growth_temperature == 27)

#Calculate delta Fv/Fm with selected timepoints
FvFm.df4 <- FvFm.df3 %>%
  dplyr::select(EE_treatment, Growth_temperature, Lineage, FvFm) %>%
  group_by(Lineage) %>%
  mutate(Delta_FvFm = ((FvFm[Growth_temperature == 31])-(FvFm[Growth_temperature == 27]))) %>%
  dplyr::select(EE_treatment, Lineage, Delta_FvFm) %>%
  distinct() %>%
  ungroup()

#Calculate progression of Fv/Fm across DHWs (growth cycle 1)
FvFm.df5 <- FvFm.df2 %>%
  filter(Nutrient_treatment == 'IMK') %>%
  filter(Growth_cycle == 1) %>%
  filter(Growth_temperature == 31 | Growth_temperature == 27) %>%
  mutate(MMM = 28.38482) %>% #MMM = maximum monthly mean
  mutate(Bleaching_threshold = MMM + 1) %>%
  mutate(Growth_temperature = as.numeric(as.character(Growth_temperature))) %>%
  mutate(Hotspot = case_when(Growth_temperature == 31 ~ Growth_temperature - Bleaching_threshold,
                             Growth_temperature == 27 ~ 0)) %>%
  mutate(DHW = Hotspot*(Time_day/7)) %>%
  mutate(DHW= round(DHW, digits = 1)) %>%
  mutate(DHW = as.character(DHW)) %>%
  mutate(Temp_DHW = str_c(.$Growth_temperature,"_", .$DHW)) %>%
  ungroup()

#Calculate delta FvFm
FvFm.df6 <- FvFm.df5 %>%
  dplyr::select(EE_treatment, Lineage, FvFm, DHW) %>%
  group_by(Lineage) %>%
  mutate(Delta_FvFm = ((FvFm[DHW == 4.8])-(FvFm[DHW == 0]))) %>%
  dplyr::select(EE_treatment, Lineage, Delta_FvFm) %>%
  distinct() %>%
  ungroup()
```

# Test for significant differences between experimental evolution treatments (Fv/Fm)
```{r}
#Check anova assumptions (QQplots to check for normal distribution)
aov.FvFm_27C <- aov(FvFm ~ EE_treatment, data = FvFm.df3[FvFm.df3$Growth_temperature == 27, ])
qqnorm(aov.FvFm_27C$residuals) 
qqline(aov.FvFm_27C$residuals)

aov.FvFm_29C <- aov(FvFm ~ EE_treatment, data = FvFm.df3[FvFm.df3$Growth_temperature == 29, ])
qqnorm(aov.FvFm_29C$residuals) 
qqline(aov.FvFm_29C$residuals)

aov.FvFm_31C <- aov(FvFm ~ EE_treatment, data = FvFm.df3[FvFm.df3$Growth_temperature == 31, ])
qqnorm(aov.FvFm_31C$residuals) 
qqline(aov.FvFm_31C$residuals)
#QQplots look ok

#Check anova assumptions (boxplots to check for equal variance)
boxplot(FvFm ~ EE_treatment, xlab='EE_treatment', ylab='Tm', data = FvFm.df3[FvFm.df3$Growth_temperature == 27, ])
boxplot(FvFm ~ EE_treatment, xlab='EE_treatment', ylab='Tm', data = FvFm.df3[FvFm.df3$Growth_temperature == 29, ])
boxplot(FvFm ~ EE_treatment, xlab='EE_treatment', ylab='Tm', data = FvFm.df3[FvFm.df3$Growth_temperature == 31, ])
#Homogeneity of variances looks ok

#Check for significant differences between experimental evolution treatments (using Tukey’s HSD)
tukey_hsd.FvFm_27C <- aov(FvFm ~ EE_treatment, data = FvFm.df3[FvFm.df3$Growth_temperature == 27, ]) %>% 
  tukey_hsd() %>%
  filter(p.adj < 0.05) %>%
  mutate(Growth_temperature = 27)

tukey_hsd.FvFm_29C <- aov(FvFm ~ EE_treatment, data = FvFm.df3[FvFm.df3$Growth_temperature == 29, ]) %>%
  tukey_hsd() %>%
  filter(p.adj < 0.05) %>%
  mutate(Growth_temperature = 29)

tukey_hsd.FvFm_31C <- aov(FvFm ~ EE_treatment, data = FvFm.df3[FvFm.df3$Growth_temperature == 31, ]) %>%
  tukey_hsd() %>%
  filter(p.adj < 0.05) %>%
  mutate(Growth_temperature = 31)

tukey_hsd.FvFm <- rbind(tukey_hsd.FvFm_27C, tukey_hsd.FvFm_29C) %>%
  rbind(tukey_hsd.FvFm_31C) %>%
  mutate(Growth_temperature = as.factor(Growth_temperature))
```

# Test for significant differences between experimental evolution treatments (delta Fv/Fm)
```{r}
#Check anova assumptions (QQplots to check for normal distribution)
aov.Delta_FvFm <- aov(Delta_FvFm ~ EE_treatment, data = FvFm.df4)
qqnorm(aov.Delta_FvFm$residuals) 
qqline(aov.Delta_FvFm$residuals)
#QQplots look ok

#Check anova assumptions (boxplots to check for equal variance)
boxplot(Delta_FvFm ~ EE_treatment, xlab='EE_treatment', ylab='Tm', data = FvFm.df4)
#Homogeneity of variances looks ok

#Check for significant differences between experimental evolution treatments (using Tukey’s HSD)
tukey_hsd.Delta_FvFm <- aov(Delta_FvFm ~ EE_treatment, data = FvFm.df4) %>%
  tukey_hsd() %>%
  filter(p.adj < 0.05)
```

# Plot 
```{r}
#Plot Fv/Fm
FvFm.plot <- FvFm.df3 %>%
  ggplot() +
  geom_boxplot(aes(x = EE_treatment, y = FvFm, fill = EE_treatment)) +
  stat_pvalue_manual(tukey_hsd.FvFm, label = "p.adj.signif", y.position = c(0.46, 0.47, 0.48, 0.46, 0.49, 0.46, 0.5, 0.47,
                                                                            0.48, 0.49, 0.5, 0.51, 0.48, 0.49, 0.5,
                                                                            0.41, 0.42, 0.43), tip.length = 0.01) +
  facet_grid(.~Growth_temperature, labeller = labeller(Growth_temperature=temperature.labs), scales = ("free_y")) +
  scale_x_discrete(labels = treatment.labs, 'Experimental evolution treatment', expand =c(0,0)) +
  scale_y_continuous(expression(bold(Maximum~quantum~yield(F[v]/F[m]))), limits = c(0.3, 0.55), expand = c(0, 0)) +
  scale_colour_manual(values=c("#CC3311","#DDAA33", "#009988", "#0269A5", "#BBBBBB")) +
  scale_fill_manual(values=c("#CC3311","#DDAA33", "#009988", "#0269A5", "#BBBBBB")) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        panel.grid.major.x = element_blank(),
        panel.spacing = unit(1, "lines"),
        strip.text.x=element_text(size=14, face="bold"),
        strip.text.y=element_text(size=14, face="bold"),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face = "bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        guides(fill = FALSE)
FvFm.plot

#Plot delta Fv/Fm
Delta_FvFm.plot <- FvFm.df4 %>%
  ggplot() +
  geom_boxplot(aes(x = EE_treatment, y = Delta_FvFm, fill = EE_treatment)) +
  stat_pvalue_manual(tukey_hsd.Delta_FvFm, label = "p.adj.signif",
                     y.position = c(-0.01, 0.02, -0.01, 0, 0.01), tip.length = 0.01) +
  scale_x_discrete(labels = treatment.labs, 'Experimental evolution treatment', expand =c(0,0)) +
  scale_y_continuous(expression(bold(Δ~F[v]/F[m])), expand =c(0,0), limits = c(-0.15, 0.05)) +
  scale_colour_manual(name = 'Experimental evolution treatment',
                      values=c("#CC3311","#DDAA33", "#009988", "#0269A5", "#BBBBBB")) +
  scale_fill_manual(name = 'Experimental evolution treatment',
                    values=c("#CC3311","#DDAA33", "#009988", "#0269A5", "#BBBBBB")) +
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing = unit(1, "lines"),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.position = 'top',
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face ="bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        guides(fill = FALSE)
Delta_FvFm.plot

#Plot Fv/Fm by DHW
temp.dhw.labs <- c('27°C (0 eDHW)', '31°C (2.5 eDHW)', '31°C (4.8 eDHW)')
names(temp.dhw.labs) <- c('27_0', '31_2.5', '31_4.8')

DHW_FvFm.plot <- FvFm.df5 %>%
  ggplot(aes(x = EE_treatment, y = FvFm, fill = EE_treatment)) +
  geom_boxplot() +
  facet_grid(.~Temp_DHW, labeller = labeller(Temp_DHW=temp.dhw.labs)) +
  scale_x_discrete(labels = treatment.labs, 'Experimental evolution treatment', expand =c(0,0)) +
  scale_y_continuous(expression(bold(Maximum~quantum~yield~(F[v]/F[m]))), limits = c(0.3, 0.5), expand =c(0,0)) +
  scale_colour_manual(name = 'Experimental evolution treatment',
                      values=c("#CC3311","#DDAA33", "#009988", "#0269A5", "#BBBBBB")) +
  scale_fill_manual(values=c("#CC3311","#DDAA33", "#009988", "#0269A5", "#BBBBBB")) +
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing = unit(1, "lines"),
        strip.text.x=element_text(size=14, face="bold"),
        strip.text.y=element_text(size=14, face="bold"),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.position = 'top',
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face ="bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        guides(fill = FALSE)
DHW_FvFm.plot

#Plot delta Fv/Fm by DHW
DHW_Delta_FvFm.plot <- FvFm.df6 %>%
  ggplot() +
  geom_boxplot(aes(x = EE_treatment, y = Delta_FvFm, fill = EE_treatment)) +
  scale_x_discrete(labels = treatment.labs, 'Experimental evolution treatment', expand =c(0,0)) +
  scale_y_continuous(expression(bold(Δ~F[v]/F[m])), expand =c(0,0), limits = c(-0.2, 0)) +
  scale_colour_manual(name = 'Experimental evolution treatment',
                      values=c("#CC3311","#DDAA33", "#009988", "#0269A5", "#BBBBBB")) +
  scale_fill_manual(values=c("#CC3311","#DDAA33", "#009988", "#0269A5", "#BBBBBB")) +
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing = unit(1, "lines"),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.position = 'top',
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 14, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1, colour = "black"), 
        axis.title.y = element_text(size = 14, colour = "black", face ="bold"), 
        axis.text.y = element_text(size = 12, colour = "black")) +
        guides(fill = FALSE)
DHW_Delta_FvFm.plot
```

# Combine plots
```{r}
FvFm.plots <- cowplot::plot_grid(FvFm.plot + rremove('xlab'),
                                 Delta_FvFm.plot  + rremove('xlab'),
                                 labels = c("(b)", "(c)"),
                                 ncol = 2, align = "v",
                                 axis = "b",
                                 rel_widths = c(1, 0.5))
FvFm.plots

FvFm_DHW.plots <- cowplot::plot_grid(DHW_FvFm.plot + rremove('xlab'),
                                     DHW_Delta_FvFm.plot + rremove('xlab'),
                                     labels = c("(a)", "(b)"),
                                     ncol = 2,
                                     align = "v",
                                     axis = "b",
                                     rel_widths = c(1, 0.5))
FvFm_DHW.plots

FvFm_DHW.plots.annot <- annotate_figure(FvFm_DHW.plots,
                                       bottom = text_grob("Experimental evolution treatment", color = "black",
                                                          face = "bold", size = 14))
FvFm_DHW.plots.annot
```

# Save plots
```{r}
ggsave(plot = FvFm.plots, "TPA - FvFM plots.pdf", 
       path = "./",
       width = 10,
       height = 5,
       units = 'in',
       dpi = 600,
       device = cairo_pdf)

ggsave(plot = FvFm_DHW.plots.annot, "Fig. S15.pdf", 
       path = "./",
       width = 10,
       height = 5,
       units = 'in',
       dpi = 600,
       device = cairo_pdf)
```

# Export data
```{r}
FvFm.data_xl <- FvFm.df3 %>%
  filter(Growth_temperature == 27 | Growth_temperature == 31) %>%
  dplyr::select(Growth_temperature, Lineage, FvFm) %>%
  distinct() %>%
  arrange(by_group = Lineage) %>%
  write_xlsx(path = "./TPA - FvFm analysis.xlsx",
             col_names = TRUE, 
             format_headers = TRUE)
```
